'use client';
import * as React from 'react';

const cx=(...values:(string|false|undefined)[])=>values.filter(Boolean).join(' ');
export type Tone='info'|'success'|'warning'|'danger'|'purple'|'paused';
type DivProps=React.ComponentProps<'div'>;
export function Theme({theme='dark',density='comfortable',className,...props}:DivProps&{theme?:'dark'|'light';density?:'comfortable'|'compact'}) {
  return <div {...props} className={cx('vsg',className)} data-theme={theme} data-density={density}/>;
}
const paths={plus:'M12 4v16M4 12h16',close:'m6 6 12 12M18 6 6 18',check:'m4 12 5 5L20 6',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',menu:'M4 6h16M4 12h16M4 18h16',chevron:'m6 9 6 6 6-6',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',arrow:'M4 12h16m-6-6 6 6-6 6',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',warning:'m12 3 10 18H2L12 3M12 9v5M12 17v1',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2'};
export function Icon({name,...props}:React.ComponentProps<'svg'>&{name:keyof typeof paths}){return <svg viewBox="0 0 24 24" className="vsg-icon" aria-hidden="true" {...props}><path d={paths[name]}/></svg>;}
export function Button({variant='secondary',size='medium',busy=false,disabled,className,children,type='button',...props}:React.ComponentProps<'button'>&{variant?:'primary'|'secondary'|'ghost'|'danger';size?:'small'|'medium'|'large'|'icon';busy?:boolean}) {
  return <button {...props} type={type} className={cx('vsg-button',variant!=='secondary'&&`vsg-button--${variant}`,size!=='medium'&&`vsg-button--${size}`,className)} disabled={disabled||busy} aria-busy={busy||undefined}>{busy&&<span className="vsg-spinner" aria-hidden="true"/>}{children}</button>;
}
export function Input({className,...props}:React.ComponentProps<'input'>){return <input {...props} className={cx('vsg-input',className)}/>;}
export function Textarea({className,...props}:React.ComponentProps<'textarea'>){return <textarea {...props} className={cx('vsg-input',className)}/>;}
export function Select({className,...props}:React.ComponentProps<'select'>){return <select {...props} className={cx('vsg-input',className)}/>;}
export function Field({label,hint,error,required,children}:{label:string;hint?:string;error?:string;required?:boolean;children:(props:{id:string;'aria-describedby'?:string;'aria-invalid'?:true;required?:boolean})=>React.ReactNode}){
  const id=React.useId();return <div className="vsg-field"><label htmlFor={id}>{label}{required&&' *'}</label>{children({id,'aria-describedby':error||hint?`${id}-help`:undefined,'aria-invalid':error?true:undefined,required})}{(error||hint)&&<small id={`${id}-help`} className={error?'vsg-error':undefined}>{error||hint}</small>}</div>;
}
export function Checkbox({label,...props}:Omit<React.ComponentProps<'input'>,'type'>&{label:string}){return <label className="vsg-choice"><input {...props} type="checkbox"/>{label}</label>;}
export function Radio({label,...props}:Omit<React.ComponentProps<'input'>,'type'>&{label:string}){return <label className="vsg-choice"><input {...props} type="radio"/>{label}</label>;}
export function Switch({label,...props}:Omit<React.ComponentProps<'input'>,'type'|'role'>&{label:string}){return <label className="vsg-switch"><input {...props} type="checkbox" role="switch"/><span className="vsg-switch-track" aria-hidden="true"/>{label}</label>;}
export function Card({className,...props}:DivProps){return <div {...props} className={cx('vsg-card',className)}/>;}
export function Badge({tone,className,...props}:React.ComponentProps<'span'>&{tone?:Tone}){return <span {...props} className={cx('vsg-badge',tone&&`vsg-badge--${tone}`,className)}/>;}
export function Alert({tone='info',title,children,live=false,...props}:DivProps&{tone?:Tone;title:string;live?:boolean}){return <div {...props} className={cx('vsg-alert',`vsg-alert--${tone}`,props.className)} role={live?(tone==='danger'?'alert':'status'):undefined}><div><strong>{title}</strong>{children}</div></div>;}
export function EmptyState({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="vsg-empty"><h3>{title}</h3><p className="vsg-muted">{description}</p>{action}</div>;}
export function Skeleton({className,...props}:DivProps){return <div {...props} className={cx('vsg-skeleton',className)} aria-hidden="true"/>;}
export function Progress({label,...props}:React.ComponentProps<'progress'>&{label:string}){return <label className="vsg-field">{label}<progress {...props}/></label>;}
export function PageHeader({title,description,actions,breadcrumbs}:{title:string;description?:string;actions?:React.ReactNode;breadcrumbs?:React.ReactNode}){return <header className="vsg-page-heading"><div>{breadcrumbs}<h1>{title}</h1>{description&&<p className="vsg-muted">{description}</p>}</div>{actions&&<div className="vsg-row">{actions}</div>}</header>;}
export function Toolbar({className,...props}:DivProps){return <div {...props} className={cx('vsg-toolbar',className)}/>;}
export function SaveBar({dirty,busy,onSave,onCancel}:{dirty:boolean;busy?:boolean;onSave:()=>void;onCancel:()=>void}){if(!dirty)return null;return <div className="vsg-save-bar"><span role="status">Есть несохранённые изменения</span><Button variant="primary" busy={busy} onClick={onSave}>{busy?'Сохранение…':'Сохранить'}</Button><Button disabled={busy} onClick={onCancel}>Отменить</Button></div>;}
export function AppShell({header,sidebar,children}:{header:React.ReactNode;sidebar:React.ReactNode;children:React.ReactNode}){return <><header className="vsg-appbar">{header}</header><div className="vsg-app-layout"><aside className="vsg-product-sidebar">{sidebar}</aside><main className="vsg-workspace">{children}</main></div></>;}
export function SplitPane({list,children,width=35}:{list:React.ReactNode;children:React.ReactNode;width?:number}){return <div className="vsg-split" style={{'--vsg-split-width':`${Math.min(60,Math.max(25,width))}%`} as React.CSSProperties}><div className="vsg-split-list">{list}</div><div className="vsg-split-detail">{children}</div></div>;}
export function Dialog({open,onOpenChange,title,children,drawer=false,theme='dark',density='comfortable'}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;children:React.ReactNode;drawer?:boolean;theme?:'dark'|'light';density?:'comfortable'|'compact'}){
  const ref=React.useRef<HTMLDialogElement>(null);const id=React.useId();
  React.useEffect(()=>{const el=ref.current;if(!el)return;if(open&&!el.open)el.showModal();if(!open&&el.open)el.close();},[open]);
  React.useEffect(()=>()=>{ref.current?.close();},[]);
  return <dialog ref={ref} className={cx('vsg','vsg-dialog',drawer&&'vsg-dialog--drawer')} data-theme={theme} data-density={density} aria-labelledby={id} onCancel={()=>onOpenChange(false)} onClose={()=>onOpenChange(false)}><div className="vsg-stack"><div className="vsg-row"><h2 id={id}>{title}</h2><Button size="icon" aria-label="Закрыть" onClick={()=>onOpenChange(false)}><Icon name="close"/></Button></div>{children}</div></dialog>;
}
export function Tabs({items,value,onValueChange,label}:{items:{id:string;label:string;content:React.ReactNode}[];value:string;onValueChange:(id:string)=>void;label:string}){
  const prefix=React.useId();const refs=React.useRef<(HTMLButtonElement|null)[]>([]);
  return <><div className="vsg-tabs" role="tablist" aria-label={label}>{items.map((item,index)=><button key={item.id} ref={el=>{refs.current[index]=el;}} id={`${prefix}-tab-${item.id}`} type="button" className="vsg-tab" role="tab" aria-selected={value===item.id} aria-controls={`${prefix}-panel-${item.id}`} tabIndex={value===item.id?0:-1} onClick={()=>onValueChange(item.id)} onKeyDown={e=>{const next=({ArrowRight:(index+1)%items.length,ArrowLeft:(index-1+items.length)%items.length,Home:0,End:items.length-1} as Record<string,number>)[e.key];if(next!==undefined){e.preventDefault();onValueChange(items[next].id);refs.current[next]?.focus();}}}>{item.label}</button>)}</div>{items.map(item=><div key={item.id} role="tabpanel" tabIndex={0} id={`${prefix}-panel-${item.id}`} aria-labelledby={`${prefix}-tab-${item.id}`} hidden={value!==item.id}>{item.content}</div>)}</>;
}
export type Option={value:string;label:string};
export function Combobox({label,options,value,onValueChange,disabled=false}:{label:string;options:Option[];value:string;onValueChange:(value:string)=>void;disabled?:boolean}){
  const id=React.useId();const [query,setQuery]=React.useState('');const [open,setOpen]=React.useState(false);const [active,setActive]=React.useState(-1);
  const filtered=options.filter(o=>o.label.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const choose=(option:Option)=>{onValueChange(option.value);setQuery('');setOpen(false);setActive(-1);};
  return <div className="vsg-field vsg-combobox"><label htmlFor={id}>{label}</label><Input id={id} disabled={disabled} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-list`} aria-activedescendant={open&&active>=0&&filtered[active]?`${id}-option-${active}`:undefined} value={open?query:options.find(o=>o.value===value)?.label||''} onFocus={()=>{setQuery('');setOpen(true);}} onBlur={()=>setOpen(false)} onChange={e=>{setQuery(e.target.value);setActive(-1);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);if(filtered.length)setActive((active+(e.key==='ArrowDown'?1:-1)+filtered.length)%filtered.length);}if(e.key==='Enter'&&open){e.preventDefault();if(filtered[active])choose(filtered[active]);}}}/><ul id={`${id}-list`} className="vsg-options" role="listbox" aria-label={label} hidden={!open}>{filtered.map((option,index)=><li id={`${id}-option-${index}`} key={option.value} role="option" aria-selected={index===active} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(option)}>{option.label}</li>)}{!filtered.length&&<li role="presentation">Ничего не найдено</li>}</ul></div>;
}
export function MultiSelect({label,options,value,onValueChange}:{label:string;options:Option[];value:string[];onValueChange:(value:string[])=>void}){return <fieldset><legend>{label}</legend>{options.map(option=><Checkbox key={option.value} label={option.label} checked={value.includes(option.value)} onChange={e=>onValueChange(e.target.checked?[...value,option.value]:value.filter(v=>v!==option.value))}/>)}</fieldset>;}
export function PasswordField({label,...props}:Omit<React.ComponentProps<'input'>,'type'>&{label:string}){const [visible,setVisible]=React.useState(false);return <Field label={label}>{field=><div className="vsg-input-group"><Input {...props} {...field} type={visible?'text':'password'}/><Button aria-pressed={visible} aria-controls={field.id} onClick={()=>setVisible(!visible)}>{visible?'Скрыть':'Показать'}</Button></div>}</Field>;}
export function NumberField({label,unit,...props}:Omit<React.ComponentProps<'input'>,'type'>&{label:string;unit:string}){const unitId=React.useId();return <Field label={label}>{field=><span className="vsg-input-group"><Input {...props} {...field} type="number" aria-describedby={unitId}/><span id={unitId}>{unit}</span></span>}</Field>;}
export function DateRange({start,end,onChange,error}:{start:string;end:string;onChange:(value:{start:string;end:string})=>void;error?:string}){return <div className="vsg-grid"><Field label="Начало периода" error={error}>{props=><Input {...props} type="date" value={start} onChange={e=>onChange({start:e.target.value,end})}/>}</Field><Field label="Конец периода" error={error}>{props=><Input {...props} type="date" value={end} onChange={e=>onChange({start,end:e.target.value})}/>}</Field></div>;}
export function TagInput({label,value,onValueChange,max=8}:{label:string;value:string[];onValueChange:(value:string[])=>void;max?:number}){const [draft,setDraft]=React.useState('');const add=()=>{const next=draft.trim();if(next&&!value.includes(next)&&value.length<max){onValueChange([...value,next]);setDraft('');}};return <div className="vsg-stack"><Field label={label} hint={`До ${max} тегов`}>{props=><div className="vsg-input-group"><Input {...props} value={draft} maxLength={30} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}}/><Button onClick={add} disabled={value.length>=max}>Добавить</Button></div>}</Field><div className="vsg-tag-list">{value.map(tag=><Badge key={tag}>{tag}<button type="button" aria-label={`Удалить тег ${tag}`} onClick={()=>onValueChange(value.filter(v=>v!==tag))}>×</button></Badge>)}</div></div>;}
export function FileUpload({label,onFile,error,accept='image/png,image/jpeg,image/webp',progress,previewUrl}:{label:string;onFile:(file:File|null)=>void;error?:string;accept?:string;progress?:number;previewUrl?:string}){const id=React.useId();return <div className="vsg-dropzone vsg-stack" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])onFile(e.dataTransfer.files[0]);}}><label className="vsg-field" htmlFor={id}>{label}</label><input id={id} type="file" accept={accept} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} onChange={e=>{onFile(e.target.files?.[0]||null);e.target.value='';}}/>{error&&<p id={`${id}-error`} className="vsg-error" role="alert">{error}</p>}{previewUrl&&<img className="vsg-file-preview" src={previewUrl} alt="Предпросмотр файла"/>}{progress!==undefined&&<Progress label="Загрузка файла" value={progress} max={100}/>}<Button onClick={()=>onFile(null)}>Очистить</Button></div>;}
export type Column<T>={key:string;label:string;render:(row:T)=>React.ReactNode;sortDirection?:'ascending'|'descending';onSort?:()=>void};
export function DataTable<T>({caption,rows,columns,getKey,selected,onSelectionChange,empty='Ничего не найдено'}:{caption:string;rows:T[];columns:Column<T>[];getKey:(row:T)=>string;selected?:string[];onSelectionChange?:(keys:string[])=>void;empty?:string}){
  return <div className="vsg-table-wrap"><table className="vsg-data-table"><caption>{caption}</caption><thead><tr>{onSelectionChange&&<th scope="col">Выбор</th>}{columns.map(col=><th key={col.key} scope="col" aria-sort={col.sortDirection}>{col.onSort?<button onClick={col.onSort} type="button">{col.label} ↕</button>:col.label}</th>)}</tr></thead><tbody>{rows.map(row=>{const key=getKey(row);return <tr key={key} aria-selected={onSelectionChange?Boolean(selected?.includes(key)):undefined}>{onSelectionChange&&<td><input type="checkbox" aria-label={`Выбрать объект ${key}`} checked={Boolean(selected?.includes(key))} onChange={e=>onSelectionChange(e.target.checked?[...(selected||[]),key]:(selected||[]).filter(v=>v!==key))}/></td>}{columns.map(col=><td key={col.key}>{col.render(row)}</td>)}</tr>;})}{!rows.length&&<tr><td colSpan={columns.length+(onSelectionChange?1:0)}>{empty}</td></tr>}</tbody></table></div>;
}
export function Pagination({page,pages,onPageChange}:{page:number;pages:number;onPageChange:(page:number)=>void}){return <nav className="vsg-row" aria-label="Страницы"><Button disabled={page<=1} onClick={()=>onPageChange(page-1)}>Назад</Button><span role="status">Страница {page} из {pages}</span><Button disabled={page>=pages} onClick={()=>onPageChange(page+1)}>Далее</Button></nav>;}
export function Accordion({title,children}:{title:string;children:React.ReactNode}){return <details className="vsg-accordion"><summary>{title}</summary><div>{children}</div></details>;}
export function Toast({message,onClose}:{message:string;onClose:()=>void}){if(!message)return null;return <div className="vsg-toast vsg-alert"><p role="status">{message}</p><Button variant="ghost" size="small" onClick={onClose} aria-label="Закрыть уведомление">×</Button></div>;}
export function Popover({label,children}:{label:string;children:React.ReactNode}){const id=React.useId();return <><Button popoverTarget={id} aria-haspopup="dialog">{label}</Button><div id={id} popover="auto" className="vsg-popover" role="dialog" aria-label={label}>{children}</div></>;}
export function Steps({items,current}:{items:string[];current:number}){return <ol className="vsg-stepper" aria-label="Этапы">{items.map((item,index)=><li key={item} aria-current={index===current?'step':undefined}>{item}</li>)}</ol>;}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="vsg-breadcrumb" aria-label="Путь">{items.map((item,index)=><React.Fragment key={item.label}>{index>0&&<span aria-hidden="true">/</span>}{item.href?<a href={item.href}>{item.label}</a>:<span aria-current={index===items.length-1?'page':undefined}>{item.label}</span>}</React.Fragment>)}</nav>;}
export function Timeline({items}:{items:{id:string;title:string;date:string;detail?:string}[]}){return <ol className="vsg-timeline">{items.map(item=><li key={item.id}><strong>{item.title}</strong><p className="vsg-muted">{item.date}</p>{item.detail&&<p>{item.detail}</p>}</li>)}</ol>;}
export function Repeater<T extends {id:string}>({label,items,renderItem,onAdd,onRemove,max=10}:{label:string;items:T[];renderItem:(item:T)=>React.ReactNode;onAdd:()=>void;onRemove:(id:string)=>void;max?:number}){return <fieldset className="vsg-stack"><legend>{label}</legend>{items.map((item,index)=><div key={item.id} className="vsg-repeat-row">{renderItem(item)}<Button onClick={()=>onRemove(item.id)} aria-label={`Удалить строку ${index+1}`}>Удалить</Button></div>)}<Button onClick={onAdd} disabled={items.length>=max}>Добавить</Button></fieldset>;}
export function BarChart({title,data}:{title:string;data:{label:string;value:number}[]}){
  const max=Math.max(1,...data.map(d=>d.value));if(!data.length)return <EmptyState title="Данных ещё нет" description="График появится после получения первых значений."/>;
  return <Card><h3>{title}</h3><svg className="vsg-chart" viewBox={`0 0 640 ${data.length*42+16}`} role="img" aria-label={title}><title>{title}; точные значения в таблице ниже</title>{data.map((d,i)=><g key={`${d.label}-${i}`}><text x="0" y={i*42+28}>{d.label}</text><rect className="vsg-chart-bar" x="150" y={i*42+10} width={Math.max(0,d.value)/max*400} height="24"/><text x="565" y={i*42+28}>{d.value}</text></g>)}</svg><Accordion title="Данные таблицей"><table><caption>{title}</caption><thead><tr><th scope="col">Период</th><th scope="col">Значение</th></tr></thead><tbody>{data.map((d,i)=><tr key={`${d.label}-${i}`}><th scope="row">{d.label}</th><td>{d.value}</td></tr>)}</tbody></table></Accordion></Card>;
}
