/* HTML catalog only: local examples, no application API, storage or image generation. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const symbols = {
    search:['Поиск','M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0'],
    plus:['Добавить','M12 4v16M4 12h16'], close:['Закрыть','m6 6 12 12M18 6 6 18'], check:['Готово','m4 12 5 5L20 6'],
    menu:['Меню','M4 6h16M4 12h16M4 18h16'], grid:['Карточки','M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z'],
    list:['Список','M8 6h13M8 12h13M8 18h13M3 6h1M3 12h1M3 18h1'],
    home:['Главная','m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9'], arrow:['Перейти','M4 12h16m-6-6 6 6-6 6'],
    chevron:['Раскрыть','m6 9 6 6 6-6'], back:['Назад','M20 12H4m6-6-6 6 6 6'], external:['Внешняя ссылка','M14 3h7v7M21 3 11 13M10 4H4v16h16v-6'],
    settings:['Настройки','M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2'],
    filter:['Фильтр','M3 4h18l-7 8v7l-4 2v-9L3 4'], sort:['Сортировка','M8 3v18m-4-4 4 4 4-4M16 21V3m-4 4 4-4 4 4'],
    edit:['Редактировать','m15 4 5 5M4 20l5-1L21 7l-4-4L5 15l-1 5'], copy:['Копировать','M8 8h13v13H8zM16 8V3H3v13h5'],
    trash:['Удалить','M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7'], archive:['Архив','M3 3h18v5H3zM5 8v13h14V8M9 12h6'],
    download:['Скачать','M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5'], upload:['Загрузить','M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5'],
    file:['Файл','M5 3h9l5 5v13H5zM14 3v6h5M8 13h8M8 17h6'], folder:['Папка','M3 5h7l2 3h9v12H3z'],
    image:['Изображение','M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M8 7h.01'], link:['Ссылка','m9 15 6-6M8 16l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 8l1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0'],
    user:['Пользователь','M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2'], users:['Участники','M14 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M2 21v-2a8 8 0 0 1 16 0v2M17 3a4 4 0 0 1 0 8M20 15a5 5 0 0 1 2 6'],
    lock:['Нет доступа','M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4M12 14v3'], bell:['Уведомления','M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4'],
    calendar:['Календарь','M3 5h18v16H3zM3 10h18M7 3v4M17 3v4M7 14h2M13 14h2'], clock:['Время','M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 7v5l3 2'],
    play:['Запустить','m7 4 14 8-14 8V4'], pause:['Пауза','M6 4h4v16H6zM14 4h4v16h-4z'], refresh:['Обновить','M20 4v6h-6M4 20v-6h6M5 8a8 8 0 0 1 13-3l2 5M4 14l2 5a8 8 0 0 0 13-3'],
    warning:['Внимание','m12 3 10 18H2L12 3M12 9v5M12 17v.1'], info:['Информация','M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 11v6M12 7v.1'],
    eye:['Показать','M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0'],
    chart:['График','M3 3v18h18M7 17v-6M12 17V7M17 17V4'], box:['Объект','m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10M7 5l9 5'],
    help:['Помощь','M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M9 8a3 3 0 0 1 6 1c0 2-3 2-3 5M12 17v.1'],
    mail:['Почта','M3 5h18v14H3zM3 5l9 8 9-8'], message:['Сообщение','M3 3h18v14H8l-5 4V3M7 8h10M7 12h7']
  };
  const svg = (name,size=20) => `<svg class="vsg-icon" style="width:${size}px;height:${size}px" viewBox="0 0 24 24" aria-hidden="true"><path d="${symbols[name]?.[1]||symbols.help[1]}"/></svg>`;
  document.querySelectorAll('[data-symbol]').forEach(el=>{el.innerHTML=svg(el.dataset.symbol,Number(el.dataset.size)||20);});
  function toast(message){$('visual-toast').hidden=false;$('visual-toast-text').textContent=message;}
  $('visual-toast-close').onclick=()=>{$('visual-toast').hidden=true;};
  document.body.addEventListener('click',event=>{const feedback=event.target.closest('[data-feedback]');if(feedback)toast(feedback.dataset.feedback);const opener=event.target.closest('[data-dialog-open]');if(opener){const dialog=$(opener.dataset.dialogOpen);dialog.returnValue='';dialog.showModal();}});
  $('visual-theme').onchange=e=>{document.body.dataset.theme=e.target.value;};
  $('confirm-dialog').addEventListener('close',()=>{if($('confirm-dialog').returnValue==='archive')toast('Демо: проект архивирован. Данные приложения не изменены.');});
  if(document.fonts){document.fonts.load('400 16px Manrope','Аа Бб 0123').then(faces=>{$('font-status').textContent=faces.length?'Локальный Manrope загружен. Кириллица и латиница доступны.':'Используется запасной системный шрифт. Проверьте доступ к файлу Manrope.';}).catch(()=>{$('font-status').textContent='Не удалось загрузить Manrope. Используется Segoe UI / Arial.';});}
  const lanes={planned:'Запланировано',working:'В работе',done:'Готово'};
  const cards=[{id:'brief',title:'Подготовить описание проекта',text:'Краткая задача с одним действием.',lane:'planned',owner:'Анна'},{id:'catalog',title:'Уточнить структуру большого каталога оборудования',text:'Длинный заголовок переносится. Расстояние до метаданных остаётся одинаковым.',lane:'planned',owner:'Иван'},{id:'layout',title:'Собрать макет главной страницы',text:'Заголовок, описание, действия и адаптация к мобильному экрану.',lane:'working',owner:'Мария'},{id:'review',title:'Проверить подписи полей',text:'Результат готов к просмотру.',lane:'done',owner:'Анна'}];
  function renderBoard(focusId){for(const key of Object.keys(lanes)){const target=document.querySelector(`[data-lane="${key}"]`);target.innerHTML=cards.filter(c=>c.lane===key).map(c=>`<article class="vsg-card vsg-board-card"><h4>${escape(c.title)}</h4><p>${escape(c.text)}</p><div class="vsg-meta-line">${escape(c.owner)} · Проект</div><footer><label class="vsg-field" for="move-${c.id}">Колонка<select class="vsg-input" id="move-${c.id}" data-move="${c.id}">${Object.entries(lanes).map(([value,label])=>`<option value="${value}" ${value===c.lane?'selected':''}>${label}</option>`).join('')}</select></label></footer></article>`).join('')||'<p class="vsg-caption">В колонке пока нет карточек.</p>';document.querySelector(`[data-count="${key}"]`).textContent=String(cards.filter(c=>c.lane===key).length);}if(focusId)$(`move-${focusId}`).focus();}
  $('visual-board').onchange=e=>{const id=e.target.dataset.move;if(!id)return;const card=cards.find(c=>c.id===id);card.lane=e.target.value;renderBoard(id);$('board-result').textContent=`«${card.title}» перемещена в «${lanes[card.lane]}».`;};renderBoard();
  const members=[{id:'anna',name:'Анна Смирнова',role:'Дизайнер',group:'Команда',initials:'АС'},{id:'ivan',name:'Иван Петров',role:'Разработчик',group:'Команда',initials:'ИП'},{id:'maria',name:'Мария Волкова',role:'Менеджер',group:'Команда',initials:'МВ'},{id:'nikita',name:'Никита Соколов',role:'Аналитик',group:'Команда',initials:'НС'},{id:'guest',name:'Гостевой участник',role:'Нет прав на этот проект',group:'Внешние участники',initials:'ГУ',disabled:true}];
  let confirmed=new Set(['anna']);let draft=new Set();let visible=[];
  function renderMembers(){const query=$('member-search').value.trim().toLocaleLowerCase('ru');visible=members.filter(m=>(m.name+' '+m.role).toLocaleLowerCase('ru').includes(query));$('member-list').innerHTML=visible.map(m=>`<li><label><input type="checkbox" data-member="${m.id}" ${draft.has(m.id)?'checked':''} ${m.disabled?'disabled':''} aria-label="${escape(m.name)}" aria-describedby="member-help-${m.id}"><span class="vsg-avatar" aria-hidden="true">${m.initials}</span><span class="vsg-choice-text"><strong>${escape(m.name)}</strong><small id="member-help-${m.id}">${escape(m.role)}</small></span><span class="vsg-badge">${m.group}</span></label></li>`).join('');$('no-members').hidden=visible.length>0;$('member-results').textContent=`Найдено: ${visible.length}. Выбор сохраняется при изменении поиска.`;updatePickerCount();}
  function updatePickerCount(){const available=visible.filter(m=>!m.disabled);const checked=available.filter(m=>draft.has(m.id)).length;$('select-visible').checked=available.length>0&&checked===available.length;$('select-visible').indeterminate=checked>0&&checked<available.length;$('select-visible').disabled=available.length===0;$('draft-count').textContent=`Выбрано: ${draft.size}`;}
  $('open-picker').onclick=()=>{draft=new Set(confirmed);$('member-search').value='';$('member-picker').returnValue='';renderMembers();$('member-picker').showModal();};
  $('member-search').oninput=renderMembers;
  $('member-search').onkeydown=e=>{if(e.key==='Enter')e.preventDefault();};
  $('member-list').onchange=e=>{const id=e.target.dataset.member;if(!id)return;e.target.checked?draft.add(id):draft.delete(id);updatePickerCount();};
  $('select-visible').onchange=e=>{visible.filter(m=>!m.disabled).forEach(m=>e.target.checked?draft.add(m.id):draft.delete(m.id));renderMembers();};
  $('clear-draft').onclick=()=>{draft.clear();renderMembers();};
  $('member-picker').addEventListener('close',()=>{if($('member-picker').returnValue!=='apply')return;confirmed=new Set(draft);$('confirmed-selection').textContent=members.filter(m=>confirmed.has(m.id)).map(m=>m.name).join(', ')||'Участники не выбраны';toast(`Выбор применён: ${confirmed.size}.`);});
  function renderIcons(){const query=$('icon-search').value.toLocaleLowerCase('ru').trim();const entries=Object.entries(symbols).filter(([name,[label]])=>(name+' '+label).toLocaleLowerCase('ru').includes(query));$('icon-gallery').innerHTML=entries.map(([name,[label]])=>`<div class="vsg-icon-tile">${svg(name)}<small>${label}</small></div>`).join('');$('icon-count').textContent=entries.length?`Показано ${entries.length} из ${Object.keys(symbols).length} иконок.`:'Иконок не найдено. Попробуйте другое название.';}$('icon-search').oninput=renderIcons;renderIcons();
  const base='Визуальный стиль V-STAR Group: сдержанная технологичная эстетика, чистая геометрия и один смысловой центр. Палитра: глубокий сине-зелёный #061014 / #091820, поверхности #0D2028 / #102A33, небольшой лаймовый акцент #D8FF18, умеренный контровой свет cyan #24D4EE. Матовый графит, тёмный металл, аккуратное стекло. Реалистичные материалы, мягкий студийный свет, контролируемые отражения, ясный силуэт. Цветовые коды — ориентир художественного направления.';
  const variants={hero:'Назначение: главный экран сайта, формат 16:9. Основной объект справа, слева 45% спокойного тёмного пространства под HTML-заголовок и кнопки. Важные детали не ближе 8% к краям. Камера на уровне объекта, ракурс три четверти. Объект читается при уменьшении и кадрировании.',product:'Назначение: карточка продукта, формат 4:3. Один объект по центру, три четверти, одинаковый масштаб с другими карточками серии. Оставить 12% воздуха по краям. Простой тёмный фон, мягкая контактная тень. Без встроенного интерфейса и мелких надписей.',service:'Назначение: иллюстрация услуги, формат 1:1. Один ясный предмет или простая композиция из двух связанных элементов. Минимум мелких деталей, узнаваемый силуэт при размере 96 px. Один лаймовый элемент. Чистый фон, без рамки. Если требуется прозрачность — настоящий alpha-канал, не рисунок шахматной сетки.',background:'Назначение: ненавязчивый фон секции, формат 21:9. Абстрактные крупные геометрические формы, низкая детализация и низкий контраст в центральной зоне. Акценты расположить ближе к краям. Фон не должен конкурировать с текстом и кнопками.',empty:'Назначение: иллюстрация пустого состояния, формат 1:1. Простая дружелюбная композиция, лёгкая глубина, один небольшой лаймовый акцент. Без драматизма, без предупреждающих знаков, если это не ошибка. Объект различим в размере 160 px. Подпись и действие будут добавлены в HTML.',editorial:'Назначение: редакционная фотография для технологического сайта, формат 3:2. Правдоподобная современная рабочая среда, естественные материалы и свет. Сдержанная цветокоррекция в сине-зелёных тонах с небольшими лаймовыми деталями. Если есть люди — естественная анатомия и позы, без карикатурной обработки. Без читаемых данных на экранах.'};
  const avoid='Исключить: текст, буквы, цифры, логотипы, водяные знаки, интерфейсные кнопки, случайные символы, чрезмерное неоновое свечение, радугу, пурпурно-розовые градиенты, визуальный шум, мелкие декоративные элементы, размытую геометрию и искажённые объекты. Не рисовать логотип V-STAR: исходный знак будет добавлен отдельно.';
  function renderPrompt(){$('image-prompt-text').value=`${base}\n\nОбъект / тема: ${$('prompt-subject').value.trim()||'[укажите объект или тему]'}.\n\n${variants[$('prompt-kind').value]}\n\n${avoid}\n\nДля серии: сохранять ракурс, свет, палитру, масштаб и уровень детализации. Использовать один утверждённый референс стиля для всей серии.`;$('copy-result').textContent='';}
  $('prompt-kind').onchange=renderPrompt;$('prompt-subject').oninput=renderPrompt;renderPrompt();
  $('select-prompt').onclick=()=>{$('image-prompt-text').focus();$('image-prompt-text').select();$('copy-result').textContent='Текст выделен. Нажмите Ctrl+C / ⌘C.';};
  $('copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText($('image-prompt-text').value);$('copy-result').textContent='Промпт скопирован.';}catch{$('select-prompt').click();}};
  const shell=$('assembled-shell');
  $('shell-menu-toggle').onclick=()=>{const hidden=!shell.hasAttribute('data-menu-hidden');shell.toggleAttribute('data-menu-hidden',hidden);$('shell-menu-toggle').setAttribute('aria-expanded',String(!hidden));};
  function setCompact(compact){shell.toggleAttribute('data-menu-compact',compact);$('sidebar-density-toggle').setAttribute('aria-pressed',String(compact));$('sidebar-density-toggle').textContent=compact?'Развернуть меню':'Компактное меню';}
  $('sidebar-density-toggle').onclick=()=>setCompact(!shell.hasAttribute('data-menu-compact'));
  document.querySelectorAll('.vsg-sidebar-group summary').forEach(summary=>summary.addEventListener('click',event=>{if(shell.hasAttribute('data-menu-compact')){event.preventDefault();setCompact(false);summary.parentElement.open=true;}}));
  document.querySelectorAll('.vsg-side-item').forEach(button=>{button.title=button.textContent.trim();button.setAttribute('aria-label',button.textContent.trim());});
  document.querySelectorAll('[data-shell-page]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-shell-page]').forEach(item=>item.removeAttribute('aria-current'));button.setAttribute('aria-current','page');$('shell-page-title').textContent=button.dataset.shellPage;$('shell-page-description').textContent=`Открыт раздел «${button.dataset.shellPage}». Это пример каркаса; данные приложения не изменяются.`;if(matchMedia('(max-width:760px)').matches){shell.setAttribute('data-menu-hidden','');$('shell-menu-toggle').setAttribute('aria-expanded','false');$('shell-page-title').focus();}});
  $('shell-space').onchange=e=>{$('shell-context').textContent=e.target.value;};
  const profileTrigger=document.querySelector('.vsg-profile-trigger');
  $('visual-profile').addEventListener('toggle',event=>{if(event.newState!=='open')return;const rect=profileTrigger.getBoundingClientRect();const menu=$('visual-profile');menu.style.right=`${Math.max(16,innerWidth-rect.right)}px`;menu.style.top=`${Math.max(16,Math.min(rect.bottom+8,innerHeight-menu.offsetHeight-16))}px`;});
  function prepareProfile(){$('profile-name-input').value=$('profile-menu-name').textContent;$('profile-edit-dialog').returnValue='';}
  $('profile-edit-open').onclick=()=>{prepareProfile();$('visual-profile').hidePopover();$('profile-edit-dialog').showModal();};
  document.body.addEventListener('click',event=>{if(event.target.closest('[data-dialog-open="profile-edit-dialog"]'))prepareProfile();},true);
  $('profile-switch-space').onclick=()=>{$('visual-profile').hidePopover();$('shell-space').focus();};
  $('profile-edit-form').addEventListener('submit',event=>{if(event.submitter?.value==='save'&&!$('profile-name-input').value.trim()){event.preventDefault();$('profile-name-input').setCustomValidity('Укажите имя.');$('profile-name-input').reportValidity();}});
  $('profile-name-input').oninput=()=>{$('profile-name-input').setCustomValidity('');};
  $('profile-edit-dialog').addEventListener('close',()=>{if($('profile-edit-dialog').returnValue!=='save')return;const name=$('profile-name-input').value.trim();$('profile-menu-name').textContent=name;profileTrigger.querySelector('strong').textContent=name;profileTrigger.setAttribute('aria-label',`Открыть меню пользователя ${name}`);const initials=name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toLocaleUpperCase('ru');profileTrigger.querySelector('.vsg-avatar').textContent=initials;$('visual-profile').querySelector('.vsg-avatar').textContent=initials;toast('Имя обновлено только в HTML-примере.');});
  const logoVariants={symbol:'Подготовь только самостоятельный знак без надписи, чтобы его можно было использовать как иконку приложения. Композиция 1:1, знак по центру, ровные поля 15%.',lockup:'Подготовь горизонтальную композицию: знак слева, точное название продукта справа. Название набрать спокойным геометрическим гротеском, совместимым с Manrope; без декоративных искажений букв. Под знаком отдельно подготовить чистую версию без текста для последующей ручной сборки.',family:'Покажи три согласованных применения одного выбранного знака: самостоятельная иконка 1:1, горизонтальный знак с названием и одноцветная версия. Это один логотип в разных применениях, а не три разных концепции. Не добавляй перспективные мокапы.'};
  function renderLogoPrompt(){const name=$('logo-product-name').value.trim()||'[НАЗВАНИЕ ПРОДУКТА]';const purpose=$('logo-product-purpose').value.trim()||'[НАЗНАЧЕНИЕ]';const concept=$('logo-product-concept').value.trim()||'[КЛЮЧЕВАЯ ИДЕЯ]';$('logo-prompt-text').value=`Разработай концепцию логотипа цифрового продукта «${name}» семейства V-STAR Group.\n\nНазначение: ${purpose}.\nКлючевая идея: ${concept}. Найди одну простую визуальную метафору, связанную именно с этой идеей; не используй случайную звезду, робота или букву V, если это не объясняется смыслом продукта.\n\nСемейное сходство: уверенная геометрия, чёткий силуэт, аккуратные углы и пропорции, модульность и ощущение движения. Используй оригинальный логотип V-STAR Group как референс языка форм, если он приложен, но не копируй его знак и не изменяй корпоративный логотип. Продукт должен иметь собственный узнаваемый символ.\n\nПалитра: основной лайм #D8FF18 на глубоком сине-зелёном #061014. Допустимый вспомогательный cyan #24D4EE — только если нужен; не более двух цветов в знаке. Предусмотри одноцветное воспроизведение и версию для светлого фона. HEX — ориентир; точный цвет фиксируется при векторной подготовке.\n\nФорма: плоская векторная эстетика, 1–3 простые формы, выразительное негативное пространство, без тонких линий. Проверка силуэта на 16, 24 и 32 px. Знак должен оставаться узнаваемым без цвета.\n\n${logoVariants[$('logo-product-variant').value]}\n\nИсключить: 3D, градиенты, тени, свечение, металл, фотографические текстуры, слишком мелкие детали, водяные знаки, слоганы, выдуманные буквы, имитации известных логотипов. Не перерисовывать исходный логотип группы. Если модель не может точно набрать название, оставить знак без текста: надпись и строка «by V-STAR Group» будут собраны вручную.\n\nРезультат — концепт на чистом фоне. Финальный SVG, точную типографику и юридическую проверку уникальности выполнять отдельно; не выдавать растровый результат за готовый вектор.`;$('logo-copy-status').textContent='';}
  ['logo-product-name','logo-product-purpose','logo-product-concept'].forEach(id=>$(id).oninput=renderLogoPrompt);$('logo-product-variant').onchange=renderLogoPrompt;renderLogoPrompt();
  $('select-logo-prompt').onclick=()=>{$('logo-prompt-text').focus();$('logo-prompt-text').select();$('logo-copy-status').textContent='Текст выделен. Нажмите Ctrl+C / ⌘C.';};
  $('copy-logo-prompt').onclick=async()=>{try{await navigator.clipboard.writeText($('logo-prompt-text').value);$('logo-copy-status').textContent='Промпт скопирован.';}catch{$('select-logo-prompt').click();}};
})();
